### ISSUE TITLE
[shards install] shard name () doesn't match dependency name (financialmodelingprep)

### ISSUE THREAD

**Issue by grokify** [grokify/crystal-financialmodelingprep#3]
From a dependent:

```bash
% shards install
Resolving dependencies
Fetching https://github.com/grokify/crystal-financialmodelingprep.git
Fetching https://github.com/mamantoha/crest.git
Fetching https://github.com/mamantoha/http-client-digest_auth.git
Fetching https://github.com/mamantoha/http_proxy.git
Error shard name () doesn't match dependency name (financialmodelingprep)
```

The following is from the dependent `shard.yml` file. No version is specified.

```yaml
dependencies:
  financialmodelingprep:
    github: grokify/crystal-financialmodelingprep
```

Unknown why the name is empty in the error message: `()`.

References:

1. `crystal-financialmodelingprep` was generated with `shardName=financialmodelingprep`
1. `crystal-financialmodelingprep`'s `shard.yml` file has `name: financialmodelingprep`
